apiVersion: v1
kind: Service
metadata:
  namespace: fiap
  name: rrestaurante-acme-pagamentos-svc
spec:
  type: LoadBalancer
  selector:
    app: rrestaurante-acme-pagamentos
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4080
      name: rrestaurante-acme-pagamentos-load-balancer
